# Generated by Django 4.1 on 2024-03-28 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.TextField()),
                ('num_base_peps', models.IntegerField()),
                ('num_peps_per_base', models.IntegerField()),
                ('min_length', models.IntegerField()),
                ('max_length', models.IntegerField()),
                ('sample_variances_down', models.IntegerField()),
                ('sample_variances_up', models.IntegerField()),
                ('sample_variances_step', models.IntegerField()),
                ('output_path', models.TextField()),
                ('user_comment', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
