# Generated by Django 4.1 on 2024-03-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_by_gaussian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='task_name',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task_list',
            name='user_comment',
            field=models.TextField(default='NA'),
        ),
    ]
