# Generated by Django 4.1 on 2024-03-30 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clip_task_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('peptides_path', models.TextField()),
                ('target_seq', models.TextField()),
                ('peps_per_target', models.IntegerField()),
                ('target_name', models.CharField(max_length=100)),
                ('output_base_path', models.TextField()),
                ('user_comment', models.TextField(default='NA')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
