# Generated by Django 4.1 on 2023-11-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_computing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetlist',
            name='output_json',
            field=models.JSONField(null=True),
        ),
    ]
