# Generated by Django 4.1 on 2024-04-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gaussianGenerateTaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=100)),
                ('dataPath', models.TextField()),
                ('numBasePeps', models.IntegerField()),
                ('numPepsPerBase', models.IntegerField()),
                ('minLength', models.IntegerField()),
                ('maxLength', models.IntegerField()),
                ('sampleVariancesDown', models.IntegerField()),
                ('sampleVariancesUp', models.IntegerField()),
                ('sampleVariancesStep', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
